version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: bookstore_postgres
    environment:
      POSTGRES_DB: bookstoremanager
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bookstore-network

volumes:
  pgdata:

networks:
  bookstore-network:
    driver: bridge